openapi: 3.0.0
info:
  title: Appointments API
  contact: {}
  version: '1.0'
servers:
- url: https://zero6-jobs-api-08192024.onrender.com/api/v1
  variables: {}
paths:
  /appointments/{id}:
    delete:
      tags:
      - Appointment
      summary: PROD_delete one appointment
      operationId: PROD_deleteoneappointment
      parameters:
      - name: id
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
    patch:
      tags:
      - Appointment
      summary: PROD_update one appointment
      operationId: PROD_updateoneappointments
      parameters:
      - name: id
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/PROD_updateoneappointmentsRequest'
              - {}
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
    parameters: []
  /appoinments:
    get:
      tags:
      - Appointment
      summary: PROD_Get all appointments
      operationId: PROD_Getallappointments
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
    parameters: []
  /appointments/{id}}:
    get:
      tags:
      - Appointment
      summary: PROD_Get one appointment
      operationId: PROD_Getoneappointment
      parameters:
      - name: id
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
    parameters: []
  /appointments:
    post:
      tags:
      - Appointment
      summary: PROD_appointments
      operationId: PROD_appointments
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/PROD_appointments_Request'
              - {}
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
    parameters: []
  /auth/login:
    post:
      tags:
      - Auth
      summary: PROD_login user
      operationId: PROD_loginuser
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/PROD_loginuserRequest'
            example:
              email: anna10@gmail.com
              password: secret
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
    parameters: []
  /auth/register:
    post:
      tags:
      - Auth
      summary: PROD register user
      operationId: PRODregisteruser
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/PRODregisteruserRequest'
            example:
              name: anna5
              email: anna5@gmail.com
              password: secret
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
    parameters: []
components:
  schemas:
    PROD_updateoneappointmentsRequest:
      title: PROD_updateoneappointmentsRequest
      required:
      - company
      - position
      type: object
      properties:
        company:
          type: string
        position:
          type: string
    PROD_loginuserRequest:
      title: PROD_loginuserRequest
      required:
      - email
      - password
      type: object
      properties:
        email:
          type: string
        password:
          type: string
    PRODregisteruserRequest:
      title: PRODregisteruserRequest
      required:
      - name
      - email
      - password
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
    PROD_appointments_Request:
      title: PROD_appointments_Request
      required:
      - company
      - position
      type: object
      properties:
        company:
          type: string
        position:
          type: string
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
security: []
tags:
- name: Appointment
  description: ''
- name: Auth
  description: ''